---
- name: 
  hosts: blender
  remote_user: root
  vars_files:
    - vars/default.yml
    - secret.yml
  tasks:
    - name: Create a user with sudo privileges
      ansible.builtin.user:
        name: "{{ create_user }}"
        state: present
        groups: sudo
        append: true
        create_home: true
        shell: /bin/bash
        password: "{{ password | password_hash('sha512', password_salt) }}"
        update_password: on_create
    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ copy_local_key }}"
    - name: Disable remote login for root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: ^PermitRootLogin yes
        line: PermitRootLogin no
    - name: Install Blender 
      snap: 
        name: blender
        classic: yes
    - name: Download .blend file 
      
        

      
